name: Morning Message

on:
  schedule:
    - cron: "0 22 * * *" # UTC 22:00 = JST 7:00
  workflow_dispatch:

jobs:
  send:
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
        
      - run: npm install
      - run: npm post
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          GPT_API_KEY_V2: ${{ secrets.GPT_API_KEY_V2 }}
          DISCORD_WEBHOOK_GENERAL: ${{ secrets.DISCORD_WEBHOOK_GENERAL }}
          DISCORD_WEBHOOK_PHRASE: ${{ secrets.DISCORD_WEBHOOK_PHRASE }}
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}